web/SSTILab/Application/models.py
from enum import unique
from . import db
from flask_login import UserMixin

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))

web/SSTILab/Application/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import os

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///database.db"
    app.config["SECRET_KEY"] = os.urandom(24)

    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = "routes.login"
    login_manager.init_app(app)

    from .models import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    from .routes import routes
    app.register_blueprint(routes)

    return app

web/SSTILab/Application/routes.py
from flask import Blueprint, flash, redirect, render_template, render_template_string, request, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import current_user, login_user, login_required, logout_user
from .models import User
from . import db

routes = Blueprint("routes", __name__)

@routes.route("/")
def index():
    return redirect(url_for("routes.blog"))

@routes.route("/blog")
@login_required
def blog():
    with open("Application/templates/blog.html", "r") as rf:
        content = rf.read().replace("$user$", current_user.username)
    return render_template_string(content)

@routes.route("/login")
def login():
    return render_template("login.html")

@routes.route("/login", methods=["POST"])
def login_post():
    if "username" in request.form.keys() and "password" in request.form.keys():

        user = User.query.filter_by(username=request.form["username"]).first()

        if not user or not check_password_hash(user.password, request.form["password"]):
            flash("Invalid credentials.")
            return redirect(url_for("routes.login"))

        login_user(user, remember=True)
        return redirect(url_for("routes.blog"))

    else:

        flash("Invalid parameters.")
        return redirect(url_for("routes.login"))

@routes.route("/register")
def register():
    return render_template("register.html")

@routes.route("/register", methods=["POST"])
def register_post():
    if "username" in request.form.keys() and "password" in request.form.keys():

        blacklist = ["'", "&", "`", "open", "config", "ls", "id", "etc", "passwd", "os", "popen" , "cat", "subprocess", "import", "system", "execute", "eval"]

        for word in blacklist:
            if word in request.form["username"] or word in request.form["password"]:
                flash("Hacker detected.")
                return redirect(url_for("routes.register"))

        if User.query.filter_by(username=request.form["username"]).first():
            flash("User already exists.")
            return redirect(url_for("routes.register"))

        user = User(username=request.form["username"], password=generate_password_hash(request.form["password"], method="sha256"))
        db.session.add(user)
        db.session.commit()

        flash("User successfully added.")
        return redirect(url_for("routes.login"))

    else:
        flash("Invalid parameters.")
        return redirect(url_for("routes.register"))

@routes.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("routes.login"))

web/SSTILab/Application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/custom.css">
    <title>Blogsite</title>
</head>
<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Blogsite</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href={{ url_for("routes.index") }}>Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={{ url_for("routes.login") }}>Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={{ url_for("routes.register") }}>Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={{ url_for("routes.blog") }}>Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={{ url_for("routes.logout") }}>Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- END NAVBAR -->

      <!-- BODY CONTENT -->
    {% block content %}{% endblock %}
      <!-- END BODY -->

      <!-- Created by Nehal Zaman (@pwnersec) with <3 -->
</body>
</html>

web/SSTILab/Application/templates/blog.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-5 container">
    <h1 class="fs-5 fw-bold">Hello $user$</h1>

    <img class="img-custom" src="/static/goku.png" alt="">

    <div class="fs-4 mt-5 mb-5">
        <p></p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non arcu risus quis varius quam quisque. In est ante in nibh mauris cursus mattis molestie. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Egestas sed tempus urna et pharetra. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Lacinia at quis risus sed vulputate odio. Imperdiet massa tincidunt nunc pulvinar. Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Turpis massa tincidunt dui ut ornare lectus sit. Mattis aliquam faucibus purus in massa. Erat velit scelerisque in dictum non consectetur a erat nam. Dolor sit amet consectetur adipiscing. Mattis vulputate enim nulla aliquet.</p>

<p>Elementum facilisis leo vel fringilla est ullamcorper eget nulla. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Fames ac turpis egestas integer eget. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Massa tincidunt nunc pulvinar sapien et ligula. Amet consectetur adipiscing elit ut aliquam purus. Bibendum ut tristique et egestas quis ipsum. Quis viverra nibh cras pulvinar mattis nunc sed. At imperdiet dui accumsan sit amet. Quam vulputate dignissim suspendisse in est ante in nibh. Volutpat consequat mauris nunc congue nisi vitae. Viverra orci sagittis eu volutpat odio facilisis mauris. Morbi tristique senectus et netus et. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Egestas sed sed risus pretium quam vulputate dignissim. Posuere lorem ipsum dolor sit. Est sit amet facilisis magna etiam tempor. Volutpat ac tincidunt vitae semper quis lectus nulla. Eget velit aliquet sagittis id. Potenti nullam ac tortor vitae.</p>

<p>Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Elementum curabitur vitae nunc sed velit dignissim sodales. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Congue nisi vitae suscipit tellus mauris a diam. Interdum varius sit amet mattis. Amet venenatis urna cursus eget. Massa sed elementum tempus egestas sed. Facilisis magna etiam tempor orci eu lobortis. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Neque viverra justo nec ultrices dui sapien. Quam elementum pulvinar etiam non quam lacus. Ornare arcu dui vivamus arcu felis bibendum ut. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Nibh ipsum consequat nisl vel pretium lectus quam. Nisl purus in mollis nunc. Quam quisque id diam vel quam elementum. In nisl nisi scelerisque eu ultrices vitae auctor.</p>

<p>Lectus urna duis convallis convallis tellus. Nunc sed velit dignissim sodales ut eu sem. Donec enim diam vulputate ut pharetra. Mattis aliquam faucibus purus in massa tempor nec. Arcu cursus vitae congue mauris rhoncus. Tellus id interdum velit laoreet id donec ultrices. Non pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Facilisis sed odio morbi quis commodo odio aenean.</p>

<p>Elementum sagittis vitae et leo. Bibendum est ultricies integer quis auctor elit. Et leo duis ut diam quam nulla porttitor. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Enim nunc faucibus a pellentesque sit amet porttitor eget. Congue quisque egestas diam in arcu cursus euismod quis. Risus ultricies tristique nulla aliquet. Venenatis a condimentum vitae sapien pellentesque habitant morbi. Ac auctor augue mauris augue. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Ut enim blandit volutpat maecenas volutpat. Rhoncus urna neque viverra justo nec ultrices dui sapien eget. Dui ut ornare lectus sit amet est placerat in.</p>

<p>Quam adipiscing vitae proin sagittis nisl. Tincidunt id aliquet risus feugiat in ante metus. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Duis convallis convallis tellus id interdum velit. Dignissim sodales ut eu sem integer. Scelerisque eleifend donec pretium vulputate sapien nec sagittis. Massa massa ultricies mi quis hendrerit dolor magna. Nec ultrices dui sapien eget mi proin sed libero enim. Nisl vel pretium lectus quam id leo in vitae turpis. Ultrices tincidunt arcu non sodales. Ut lectus arcu bibendum at varius vel.</p>

<p>Egestas pretium aenean pharetra magna ac placerat vestibulum. Consectetur adipiscing elit pellentesque habitant morbi. Purus non enim praesent elementum facilisis leo vel. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Pulvinar sapien et ligula ullamcorper malesuada proin. Pellentesque dignissim enim sit amet venenatis. Ipsum faucibus vitae aliquet nec. Integer malesuada nunc vel risus commodo viverra maecenas accumsan. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Sed elementum tempus egestas sed. Lectus mauris ultrices eros in cursus. Massa ultricies mi quis hendrerit. Non tellus orci ac auctor augue mauris augue neque gravida. Nibh mauris cursus mattis molestie a iaculis at erat.</p>
    </div>
</div>
{% endblock %}

web/SSTILab/Application/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="custom-container">
    <div class="p-5 inner-custom-container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-dark" role="alert">
                    {{ message }}
                  </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <h1 class="mt-1 mb-4 fs-2 fw-bold">Login</h1>

        <form action="/login" method="POST">

            <div class="input-group flex-nowrap">
                <input type="text" name="username" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping">
            </div>
    
            <div class="mt-2 mb-2 input-group flex-nowrap">
                <input type="password" name="password" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="addon-wrapping">
            </div>
    
            <button class="mt-2 btn btn-dark" type="submit">Login</button>

        </form>

    </div>
</div>
{% endblock %}

web/SSTILab/Application/templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="custom-container">
    <div class="p-5 inner-custom-container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-dark" role="alert">
                    {{ message }}
                  </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <h1 class="mt-1 mb-4 fs-2 fw-bold">Signup</h1>

        <form action="/register" method="POST">

            <div class="input-group flex-nowrap">
                <input type="text" name="username" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping">
            </div>
    
            <div class="mt-2 mb-2 input-group flex-nowrap">
                <input type="password" name="password" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="addon-wrapping">
            </div>
    
            <button class="mt-2 btn btn-dark" type="submit">Signup</button>

        </form>

    </div>
</div>
{% endblock %}